# Site settings
title: Yago Carballo
email: yagocarballo@gmail.com
url: https://yagocarballo.me
description: "I am a fast and avid learner who likes to solve software related problems as well as creating new and unexpected experiences through technology."
# baseurl: /yagocarballo.me

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  
# Footer settings
footer:
  copyright: Yago Carballo Porto
  location: Address
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://uk.linkedin.com/in/yagocarballo/
  - title: twitter
    url: http://twitter.com/_YagoCarballo
  - title: bitbucket 
    url: http://bitbucket.org/yagocarballo
  - title: github
    url: http://github.com/yagocarballo

# Postal address (add as many lines as necessary)
address:
  - line: <b>Spain</b>
  - line: Subida a Costa Castrelos Nº10
  - line: Vigo, Pontevedra 36213, España
  - line: 
  - line: <b>United Kingdom</b>
  - line: The Hub, 17 Hawkhill
  - line: DD1 5DL, Dundee, UK
  
# Credits content
credits: 'Feel free to contact me at <a href="mailto:yagocarballo@gmail.com">yagocarballo@gmail.com</a>'

# Build settings
markdown: kramdown
permalink: pretty
